//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Polypack.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contact
    {
        public int Id { get; set; }
        public string Info { get; set; }
        public string Num { get; set; }
        public string EmailInfo { get; set; }
        public string Email { get; set; }
        public string OpenHours { get; set; }
        public string Text { get; set; }
        public string Adress { get; set; }
        public string Photo { get; set; }
        public string Desc { get; set; }
    }
}
